package util

import (
	"encoding/json"
	"fmt"
	"math"
	"os"
	"regexp"
	"strings"
	"time"

	"github.com/QC3284/BBDown/internal/entity"
)

// SubUtil handles subtitle fetching and conversion.

// GetSubtitleCode returns the language code and display name for a subtitle language key.
func GetSubtitleCode(key string) (string, string) {
	// Fix case: zh-hans => zh-Hans
	re := regexp.MustCompile(`-[a-z]`)
	if match := re.FindString(key); match != "" {
		key = strings.Replace(key, match, strings.ToUpper(match), 1)
	}

	codes := map[string][2]string{
		"ai-Zh":    {"chi", "中文（简体, AI识别）"},
		"ai-En":    {"eng", "English(generated by ai)"},
		"zh-CN":    {"chi", "中文（简体）"},
		"zh-HK":    {"chi", "中文（香港繁體）"},
		"zh-Hans":  {"chi", "中文（简体）"},
		"zh-TW":    {"chi", "中文（台灣繁體）"},
		"zh-Hant":  {"chi", "中文（繁體）"},
		"en-US":    {"eng", "English(USA)"},
		"ja":       {"jpn", "日本語"},
		"ko":       {"kor", "한국어"},
		"zh-SG":    {"chi", "中文（新加坡）"},
		"yue":      {"chi", "粵語"},
		"yue-HK":   {"chi", "粵語（中國香港）"},
		"en":       {"eng", "English"},
		"en-CA":    {"eng", "English(Canada)"},
		"en-IE":    {"eng", "English(Ireland)"},
		"en-GB":    {"eng", "English(UK)"},
		"fr":       {"fre", "Français"},
		"fr-BE":    {"fre", "Français(Belgique)"},
		"fr-CA":    {"fre", "Français(Canada)"},
		"fr-FR":    {"fre", "Français(La France)"},
		"fr-CH":    {"fre", "Français(Suisse)"},
		"de":       {"ger", "Deutsch"},
		"de-AT":    {"ger", "Deutsch(Österreich)"},
		"de-DE":    {"ger", "Deutsch(Deutschland)"},
		"de-CH":    {"ger", "Deutsch(Schweiz)"},
		"es":       {"spa", "Español"},
		"es-419":   {"spa", "Español(Latinoamérica)"},
		"es-MX":    {"spa", "Español(México)"},
		"es-ES":    {"spa", "Español(España)"},
		"es-US":    {"spa", "Español(Estados Unidos)"},
		"it":       {"ita", "Italiano"},
		"pt":       {"por", "Português"},
		"pt-BR":    {"por", "Português(brasil)"},
		"pt-PT":    {"por", "Português(portugal)"},
		"ru":       {"rus", "Русский"},
		"ru-Latn":  {"rus", "Русский(фонетический)"},
		"ar":       {"ara", "العربية"},
		"th":       {"tha", "ไทย"},
		"vi":       {"vie", "Tiếng Việt"},
		"id":       {"ind", "Indonesia"},
		"tr":       {"tur", "Türkçe"},
		"uk":       {"ukr", "Українська"},
		"pl":       {"pol", "Polski"},
		"nl":       {"dut", "Nederlands"},
		"nl-BE":    {"dut", "Nederlands(Belgisch)"},
		"nl-NL":    {"dut", "Nederlands(Nederlands)"},
		"sv":       {"swe", "Svenska"},
		"no":       {"nor", "norsk språk"},
		"da":       {"dan", "Dansk"},
		"fi":       {"fin", "Suomi"},
		"cs":       {"cze", "čeština"},
		"hu":       {"hun", "Magyar"},
		"ro":       {"rum", "Română"},
		"el":       {"gre", "Ελληνικά"},
		"he":       {"heb", "שפה עברית"},
		"iw":       {"heb", "שפה עברית"},
		"hi":       {"hin", "हिन्दी"},
		"hi-Latn":  {"hin", "हिंदी(फोनेटिक)"},
		"bn":       {"ben", "বাংলা ভাষার"},
		"ta":       {"tam", "தமிழ்"},
		"te":       {"tel", "తెలుగు"},
		"ur":       {"urd", "Urdu"},
		"fa":       {"per", "فارسی"},
		"fa-AF":    {"per", "فارسی"},
		"fa-IR":    {"per", "فارسی"},
		"ms":       {"may", "Melayu"},
		"fil":      {"phi", "Pilipino"},
		"tl":       {"tgl", "Tagalog"},
		"bg":       {"bul", "български"},
		"sr":       {"srp", "Српски"},
		"sr-Cyrl":  {"srp", "Српски(ћирилица)"},
		"sr-Latn":  {"srp", "Српски(латиница)"},
		"hr":       {"hrv", "Hrvatska"},
		"sk":       {"slo", "slovenský"},
		"sl":       {"slv", "slovenščina"},
		"lt":       {"lit", "lietuvių kalba"},
		"lv":       {"lav", "latviešu valoda"},
		"et":       {"est", "Eestlane"},
		"sq":       {"alb", "Gjuha shqipe"},
		"mk":       {"mac", "Македонски јазик"},
		"ka":       {"geo", "ქართული ენა"},
		"hy":       {"arm", "հայերեն"},
		"az":       {"aze", "Azərbaycan"},
		"eu":       {"baq", "Euskara"},
		"ca":       {"cat", "català"},
		"gl":       {"glg", "galego"},
		"is":       {"ice", "icelandic"},
		"ga":       {"gle", "Gaeilge na hÉireann"},
		"cy":       {"wel", "Cymraeg"},
		"mn":       {"mon", "монгол хэл"},
		"kk":       {"kaz", "Қазақ тілі"},
		"ky":       {"kir", "кыргыз тили"},
		"km":       {"khm", "ភាសាខ្មែរ"},
		"lo":       {"lao", "ພາສາລາວ"},
		"my":       {"bur", "မြန်မာဘာသာ"},
		"ne":       {"nep", "नेपाली Nepālī"},
		"kn":       {"kan", "ಕನ್ನಡ"},
		"ml":       {"mal", "മലയാളം"},
		"mr":       {"mar", "मराठी Marāṭhī"},
		"gu":       {"guj", "ગુજરાતી"},
		"pa":       {"pan", "ਪੰਜਾਬੀ"},
		"am":       {"amh", "አማርኛ"},
		"sw":       {"swa", "Kiswahili"},
		"zu":       {"zul", "isiZulu"},
		"af":       {"afr", "Afrikaans"},
		"lb":       {"ltz", "Lëtzebuergesch"},
		"mt":       {"mlt", "Lingwa Maltija"},
		"bs":       {"bos", "босански"},
		"mi":       {"mao", "Māori"},
		"jv":       {"jav", "ꦧꦱꦗꦮ"},
		"la":       {"lat", "latīna"},
		"eo":       {"epo", "Esperanto"},
		"fo":       {"fao", "føroyskt"},
		"ff":       {"ful", "Fulani"},
		"ha":       {"hau", "هَوُسَ"},
		"ig":       {"ibo", "Asụsụ Igbo"},
		"rw":       {"kin", "Ikinyarwanda"},
		"mg":       {"mlg", "maa.laa.gaas"},
		"ln":       {"lin", "Lingála"},
		"ku":       {"kur", "Kurdî"},
		"sh":       {"scr", "srpskohrvatski"},
		"co":       {"cos", "lingua corsa"},
		"br":       {"bre", "Breton"},
		"bi":       {"bis", "Bislama"},
		"na":       {"nau", "Dorerin Naoero"},
		"sm":       {"smo", "Gagana Samoa"},
		"to":       {"ton", "lea faka-Tonga"},
		"fj":       {"fij", "Vakaviti"},
		"kl":       {"kal", "Kalaallisut"},
		"dv":       {"div", "ދިވެހި"},
		"dz":       {"dzo", "རྫོང་ཁ།"},
		"gn":       {"grn", "avañe'ẽ"},
		"ay":       {"aym", "Aymar aru"},
		"qu":       {"que", "Runasimi"},
		"ik":       {"ipk", "Inupiat"},
		"iu":       {"iku", "ᐃᓄᒃᑎᑐᑦ"},
		"nv":       {"nav", "Diné bizaad"},
		"chr":      {"chr", "ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ"},
		"cho":      {"cho", "Chahta'"},
		"mas":      {"mas", "Maasai"},
		"ab":       {"abk", "Аҳәынҭқарра"},
		"aa":       {"aar", "Qafár af"},
		"su":       {"sun", "Basa Sunda"},
		"tt":       {"tat", "татарча"},
		"uz":       {"uzb", "Oʻzbekcha"},
		"yi":       {"yid", "ייִדיש"},
		"yo":       {"yor", "Yorùbá"},
		"xh":       {"xho", "isiXhosa"},
		"wo":       {"wol", "Wolof"},
		"fy":       {"fry", "Frysk"},
		"st":       {"sot", "Sesotho"},
		"ts":       {"tso", "Xitsonga"},
		"tn":       {"tsn", "Setswana"},
		"sn":       {"sna", "chiShona"},
		"sg":       {"sag", "Sängö"},
		"sa":       {"san", "संस्कृतम्"},
		"oc":       {"oci", "Occitan"},
		"or":       {"ori", "ଓଡ଼ିଆ"},
		"om":       {"orm", "Afaan Oromoo"},
		"ps":       {"pus", "پښتو"},
		"rm":       {"roh", "Rumantsch"},
		"rn":       {"run", "Ikirundi"},
		"sd":       {"snd", "सिन्धी"},
		"si":       {"sin", "සිංහල"},
		"so":       {"som", "Soomaali"},
		"ss":       {"ssw", "SiSwati"},
		"tg":       {"tgk", "тоҷикӣ"},
		"ti":       {"tir", "ትግርኛ"},
		"tk":       {"tuk", "Türkmençe"},
		"tw":       {"twi", "Twi"},
		"vo":       {"vol", "Volapük"},
		"ie":       {"ile", "Interlingue"},
		"ia":       {"ina", "Interlingua"},
		"ase":      {"ase", "American Sign Language"},
		"arc":      {"arc", "ܐܪܡܝܐ"},
		"ba":       {"bak", "Башҡорттеле"},
		"bh":       {"bih", "Bihar"},
		"lus":      {"lus", "Mizo ṭawng"},
		"mo":       {"mol", "Limba moldovenească"},
		"tlh":      {"tlh", "tlhIngan Hol"},
		"hak":      {"hak", "Hak-kâ-fa"},
		"hak-TW":   {"hak", "Hak-kâ-fa"},
		"nan":      {"nan", "閩南語"},
		"nan-TW":   {"nan", "閩南語(台灣)"},
	}

	if v, ok := codes[key]; ok {
		return v[0], v[1]
	}
	return "und", "Undetermined"
}

// FormatSubtitleTime formats seconds to SRT time format: HH:MM:SS,mmm
func FormatSubtitleTime(sec float64) string {
	if math.IsNaN(sec) || sec < 0 {
		sec = 0
	}
	if sec > 1<<63/1e7 {
		sec = 1<<63/1e7 - 1
	}
	d := time.Duration(sec * float64(time.Second))
	hours := int64(d.Hours())
	minutes := int64(d.Minutes()) % 60
	seconds := int64(d.Seconds()) % 60
	millis := d.Milliseconds() % 1000
	return fmt.Sprintf("%02d:%02d:%02d,%03d", hours, minutes, seconds, millis)
}

// SanitizeSRTContent cleans subtitle content for valid SRT format.
func SanitizeSRTContent(content string) string {
	if content == "" {
		return ""
	}
	content = strings.ReplaceAll(content, "\r\n", "\n")
	content = strings.ReplaceAll(content, "\r", "\n")
	lines := strings.Split(content, "\n")
	var kept []string
	for _, l := range lines {
		l = strings.TrimRight(l, " \t")
		if len(l) > 0 {
			kept = append(kept, l)
		}
	}
	return strings.Join(kept, "\n")
}

// ConvertSubFromJSON converts Bilibili JSON subtitle format to SRT.
func ConvertSubFromJSON(jsonStr string) string {
	var data struct {
		Body []struct {
			From    float64 `json:"from"`
			To      float64 `json:"to"`
			Content string  `json:"content"`
		} `json:"body"`
	}
	if err := json.Unmarshal([]byte(jsonStr), &data); err != nil {
		return ""
	}
	var sb strings.Builder
	for i, line := range data.Body {
		sb.WriteString(fmt.Sprintf("%d\n", i+1))
		sb.WriteString(fmt.Sprintf("%s --> %s\n", FormatSubtitleTime(line.From), FormatSubtitleTime(line.To)))
		sb.WriteString(SanitizeSRTContent(line.Content) + "\n\n")
	}
	return sb.String()
}

// SaveSubtitleAsync downloads a subtitle from url and saves it to the given path.
func SaveSubtitleAsync(httpClient *HTTPClient, url, path string) error {
	body, err := httpClient.GetWebSource(nil, url)
	if err != nil {
		return err
	}
	if strings.HasSuffix(path, ".srt") {
		body = ConvertSubFromJSON(body)
	}
	return os.WriteFile(path, []byte(body), 0o644)
}

// GetSubtitles fetches subtitles for a video page.
// This is a simplified placeholder - the full implementation handles multiple APIs.
func GetSubtitles(httpClient *HTTPClient, aid, cid, epid string, index int, intl bool, cookie string) ([]entity.Subtitle, error) {
	// Placeholder - full implementation with multiple API fallbacks
	return nil, nil
}
